name: dbt_run_scheduled_onchain_daily
run-name: dbt_run_scheduled_onhcain_daily

on:
  workflow_dispatch:
  schedule:
    # Runs 03:00 UTC daily (see https://crontab.guru)
    - cron: '0 3 * * *'
    
env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

jobs:
  avalanche_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__avalanche,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit 

  ethereum_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__ethereum,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit 
  
  base_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__base,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  aptos_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__aptos,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit

  polygon_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__polygon,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  optimism_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__optimism,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit

  near_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__near,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  arbitrum_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__arbitrum,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  blast_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__blast,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  flow_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__flow,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  thorchain_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__thorchain,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  axelar_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__axelar,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
  
  sei_scores:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@main
    with:
      dbt_command: dbt run -s onchain_scores__sei,version:latest
      environment: ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: DBT_CLOUD
    secrets: inherit
